CREATE TABLE IF NOT EXISTS chat_disposition (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    session_id            BIGINT       NOT NULL,
    tenant_id             VARCHAR(64)  NOT NULL,
    lead_id               VARCHAR(64)  NOT NULL,
    agent_id              VARCHAR(64)  NOT NULL,
    channel               VARCHAR(24)  NOT NULL,
    business_phone        VARCHAR(24)  NULL,
    session_started_at    DATETIME(3)  NOT NULL,
    session_ended_at      DATETIME(3)  NOT NULL,
    status                VARCHAR(24)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING | GENERATING | COMPLETED | FAILED | FALLBACK',
    attempt_count         INT          NOT NULL DEFAULT 0,
    summary               TEXT         NULL,
    lead_intent           TEXT         NULL,
    agent_action          TEXT         NULL,
    sentiment             VARCHAR(24)  NULL COMMENT 'POSITIVE | NEUTRAL | FRUSTRATED | ANGRY | CONFUSED',
    unresolved            TEXT         NULL,
    key_entities_json     JSON         NULL,
    model_version         VARCHAR(128) NULL,
    failure_reason        TEXT         NULL,
    crm_delivered_at      DATETIME(3)  NULL,
    converse_delivered_at DATETIME(3)  NULL,
    created_at            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_session_id (session_id),
    INDEX idx_cd_tenant_lead (tenant_id, lead_id),
    INDEX idx_cd_status (status),
    INDEX idx_cd_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
